"""Add disable fields

Revision ID: a8c97df33b71
Revises: 
Create Date: 2025-12-11 14:36:45.239705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c97df33b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('disabled_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('disabled_until')
        batch_op.drop_column('is_disabled')

    # ### end Alembic commands ###
