"""Add disabled_reason field

Revision ID: beefcfa1e31e
Revises: a8c97df33b71
Create Date: 2025-12-11 14:42:30.131005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beefcfa1e31e'
down_revision = 'a8c97df33b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('disabled_reason')

    # ### end Alembic commands ###
